texto = "Nossa aula Manipulando String."
print(texto[2])
print(len(texto))
print(texto.count("a"))
print(texto.count("a", 5, 30))
print(texto.find("aula"))
print(texto.find("python"))
print('String' in texto)
print("Raphael" in texto)
texto.split()